### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/agent/nyu_dataset/nyu_depth_v2/bedroom_0076b/r-1315244969.851995-2619100169.ppm'

### ISSUE THREAD

**Issue by agenthong** [svip-lab/Indoor-SfMLearner#11]
Hi!

Thanks for sharing this great work! I'm trying to train the model but it seems that the official dataset lacks some data(bedroom_0076b).

I download the raw data from the official website, so I'm wondering if the train files split made some mistakes or my dataset is not prepared completely.

Thanks a lot!

**Comment by niujinshuchong** [comment]
@agenthong I think you didn't download the full dataset. Please refer to #2

**Comment by agenthong** [comment]
> @agenthong I think you didn't download the full dataset. Please refer to #2

Thanks! It works.
