### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by Rock-100** [svip-lab/Indoor-SfMLearner#14]
https://github.com/svip-lab/Indoor-SfMLearner/blob/0d682b7ce292484e5e3e2161fc9fc07e2f5ca8d1/inference_single_image.py#L80

Should this be input_image = input_image.resize((thisW, thisH), pil.LANCZOS) ?

**Comment by niujinshuchong** [comment]
Hi, thanks for pointing this out! It's fixed.
