### ISSUE TITLE
inconsistent sampling methods during training and testing

### ISSUE THREAD

**Issue by Rock-100** [svip-lab/Indoor-SfMLearner#15]
https://github.com/svip-lab/Indoor-SfMLearner/blob/efc8cdc4773bee334986eefe3d16702b0ef4d07b/trainer_geo.py#L184
During training, the sampling method is 'nearest'.

https://github.com/svip-lab/Indoor-SfMLearner/blob/efc8cdc4773bee334986eefe3d16702b0ef4d07b/evaluation/nyuv2_eval_depth.py#L63
During testing, the sampling method is 'bilinear'.

**Comment by niujinshuchong** [comment]
@Rock-100 Good catch! Hope it won't change the results that much.

**Comment by Rock-100** [comment]
I have tried. The influence is minor.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by niujinshuchong** [comment]
Great! Thank you so much!
