### ISSUE TITLE
Two questions about the dataloader

### ISSUE THREAD

**Issue by Rock-100** [svip-lab/Indoor-SfMLearner#16]
Thanks for your great work!

Can I ask two questions about the dataloader?

1. In 'NYUDataset', we undistort images.
https://github.com/svip-lab/Indoor-SfMLearner/blob/efc8cdc4773bee334986eefe3d16702b0ef4d07b/datasets/nyu_dataset.py#L308
But in 'NYUTestDataset', we don't undistort images.
https://github.com/svip-lab/Indoor-SfMLearner/blob/efc8cdc4773bee334986eefe3d16702b0ef4d07b/datasets/nyu_dataset.py#L391
Is this because raw images are loaded in 'NYUDataset'?

2. Here we use self.full_res_shape (608, 448), instead of (640, 480), to compute the normalized intrinsics. Will this have a negative influence?
https://github.com/svip-lab/Indoor-SfMLearner/blob/efc8cdc4773bee334986eefe3d16702b0ef4d07b/datasets/nyu_dataset.py#L329

**Comment by niujinshuchong** [comment]
@Rock-100 

1. The NYUv2 Test image is already undistorted.
2. I think this is a bug. We intend to modify the intrinsics with 480x640 as shown in the comments above. But we forgot to update it accordingly when we crop the images. Not sure how much this affects the results but I hope it is minor again. 

Thanks again for reporting this.

**Comment by Rock-100** [comment]
Do you mean ‘The NYUv2 Test image is already UNdistorted.‘？

**Comment by niujinshuchong** [comment]
Yes.
