### ISSUE TITLE
About monodepth2 result in the paper

### ISSUE THREAD

**Issue by myalos** [svip-lab/Indoor-SfMLearner#17]
Thanks for sharing code!
How did you get this result, is it directly using the monodepth2 pre-training model for evaluation, or using monodepth2 to train on the NYUv2 dataset before evaluating.
By the way, are networks.py and partialconv.py unrelated to your paper ?

**Comment by niujinshuchong** [comment]
We trained monodepth2 on the NYUv2 dataset for baseline comparison. Yes, networks.py and partialconv.py is not used and they are part of monodepth2 code base and we built our method on top of monodepth2.

**Comment by myalos** [comment]
Thank you for quick reply!
I train monodepth2 on the NYUv2 last night. I changed the max_depth from 100 to 10, and scale from [0, 1, 2, 3] to [0]. and the result is a1 0.691 a2 0.911 a3 0.973.
Can you share the recipe of training monodepth2 on NYUv2 ?

**Comment by 1deepgroupe1** [comment]
Hello, may I ask if you have reproduced the results of training Monodepth2？

**Comment by myalos** [comment]
not exactly but nearly

**Comment by 1deepgroupe1** [comment]
Thank you for your answer. Can you explain how it was done

**Comment by myalos** [comment]
https://github.com/SJTU-ViSYS/StructDepth/issues/9

**Comment by 1deepgroupe1** [comment]
May I also ask how to convert the test data into h5 format

**Comment by 1deepgroupe1** [comment]
Thank you very much for your reply. I have a rough understanding of how to do it。

**Comment by myalos** [comment]
> May I also ask how to convert the test data into h5 format

just download h5 format test data provided by the author

**Comment by 1deepgroupe1** [comment]
Hello, did you encounter this error when using Python to read so files in window。

OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by myalos** [comment]
no, i didn't

**Comment by 1deepgroupe1** [comment]
Have you removed the following program from file nyu_dataset.py        

svo_map_resized = np.zeros((self.height, self.width)) # 288 * 384
        img = np.array(inputs[("color", 0, -1)])
        key_points = self.pixelselector.extract_points(img)                                                    
        key_points = key_points.astype(int)
        key_points[:,0] = key_points[:,0] * self.height // 480
        key_points[:,1] = key_points[:,1] * self.width // 640

        # noise 1000 points
        noise_num = 3000 - key_points.shape[0]
        noise_points = np.zeros((noise_num, 2), dtype=np.int32)
        noise_points[:, 0] = np.random.randint(self.height, size=noise_num)
        noise_points[:, 1] = np.random.randint(self.width, size=noise_num)

        svo_map_resized[key_points[:,0], key_points[:,1]] = 1

        inputs['svo_map'] = torch.from_numpy(svo_map_resized.copy())
        svo_map_resized[noise_points[:,0], noise_points[:,1]] = 1
        inputs['svo_map_noise'] = torch.from_numpy(
            svo_map_resized,
        ).float()
        keypoints = np.concatenate((key_points, noise_points), axis=0)
        inputs['dso_points'] = torch.from_numpy(
            keypoints,
        ).float()

**Comment by myalos** [comment]
yes, the code related to svo is removed

**Comment by 1deepgroupe1** [comment]
Sorry to bother you again. I changed the code as you said, but ABS appeared_ rel | sq_ rel | rmse | rmse_ the situation where these errors increase in log。I would like to know if you have any other changes? Is the loss function of monodepthv2 used?

**Comment by 1deepgroupe1** [comment]
I just ran a few epochs and found that the error was increasing, so I didn't continue training

**Comment by myalos** [comment]
maybe you should change the intrinsics parameters in dataset class like StructDepth do

**Comment by 1deepgroupe1** [comment]
What do you mean by using nyu_dataset.py in StructDepth

**Comment by myalos** [comment]
> maybe you should change the intrinsics parameters in dataset class like StructDepth do
Sfmlearner indoor and StructDepth have different settings for camera intrinsic parameters.
I changed nyu_dataset.py, options.py and trainer.py accordingly

> What do you mean by using nyu_dataset.py in StructDepth
I changed nyu_dataset.py from StructDepth to reproduce the monodepth2, not Sfmlearner indoor

**Comment by 1deepgroupe1** [comment]
I tried but the error is still rising, I don't know what the reason is. Can you share your code?

**Comment by myalos** [comment]
> I tried but the error is still rising, I don't know what the reason is. Can you share your code?
https://github.com/myalos/monodepth2nyu

**Comment by 1deepgroupe1** [comment]
An error occurred while using your code

  File "C:\Users\looper\Desktop\monodepth2nyu-master\datasets\nyu_dataset.py", line 225, in get_color
    h, w, c = color.shape
AttributeError: 'tuple' object has no attribute 'shape'

I tried using np. array (color), but an error occurred：

ValueError: could not broadcast input array from shape (480,640,3) into shape (480,640)

**Comment by myalos** [comment]
Change the scale from [0, 1, 2, 3] to [0] in options.py. that is the version i use before pushing to the github, i have run that code successfully.

> I tried using np. array (color), but an error occurred：
> 
> ValueError: could not broadcast input array from shape (480,640,3) into shape (480,640)

The error i have not met before, maybe because your path setting is not correct, please provide more detail  error message(file tree or the code you have changed)

**Comment by 1deepgroupe1** [comment]
I found that your code did not use the val function, so I added the val function in StructDepth. this is the cause of the error

**Comment by 1deepgroupe1** [comment]
I run three epochs, and this is the result of my four epochs. Do you think this result is correct?
   abs_rel |   sq_rel |     rmse | rmse_log |     lg10 |       a1 |       a2 |       a3 | 
&   0.317  &   0.433  &   0.996  &   0.362  &   0.124  &   0.523  &   0.786  &   0.907  \\
&   0.311  &   0.422  &   0.995  &   0.360  &   0.124  &   0.523  &   0.787  &   0.909  \\
&   0.311  &   0.423  &   0.998  &   0.361  &   0.124  &   0.520  &   0.786  &   0.909  \\
 &   0.311  &   0.421  &   0.993  &   0.360  &   0.123  &   0.522  &   0.787  &   0.909  \\

**Comment by myalos** [comment]
correct
