### ISSUE TITLE
nyu2 raw dataset does not match the split

### ISSUE THREAD

**Issue by huangyuan2020** [svip-lab/Indoor-SfMLearner#2]
Thank you very much for your work. When I trying to test the trainning scripts, I met some problem abour NYU2 dataset, because the entire dataset download link is failed,  I download the different parts of the dataset individually and unzip them all, but the scenes does not match the training split, such as classroom__0016 is not in the dataset I downloaded, could you give me some advice?

**Comment by niujinshuchong** [comment]
@huangyuan2020 

The raw NYU dataset is about 400G and has 590 videos. You can download the raw datasets from http://horatio.cs.nyu.edu/mit/silberman/nyu_depth_v2/nyu_depth_v2_raw.zip

The link is still working.
