### ISSUE TITLE
Keypoints extraction

### ISSUE THREAD

**Issue by ghost** [svip-lab/Indoor-SfMLearner#7]
Hi, I noticed that you've adopted the points selection strategy from DSO for its effectiveness and efficiency. Points from DSO are sampled from pixels that have large intensity gradients. I'm wondering why this strategy is effective and efficient and why not choose the sobel filter to get points with large intensity gradients?

**Comment by niujinshuchong** [comment]
@vvvsice 

I wrote a simple code to show the comparison between harris corner detector and DSO. It shows that DSO points are well-distributed in the image which, we believe, is important to train the network. But we didn't do experiments to validate that. 

![c](https://user-images.githubusercontent.com/13434986/106421319-76beff00-6497-11eb-92e9-0339c686da07.png)

**Comment by ghost** [comment]
@niujinshuchong 

Thanks for your reply. I find that the harris corner detector is designed to detect corners while DSO points selector seems to detect both corners and edges. And I think simple Sobel filter can also have the same effect, so I'm curious why not choose the Sobel filter?

**Comment by niujinshuchong** [comment]
@vvvsice 

I see. I think it will be a good idea to try.
