### ISSUE TITLE
关于得到的深度图像的颜色和深度的对应关系

### ISSUE THREAD

**Issue by yanxiaojing16** [svip-lab/Indoor-SfMLearner#8]
您好。
  我正在做本科毕设，想利用您论文里的深度估计模块，想问下得到深度图片是绝对深度还是相对深度呀，另外颜色和深度的对应关系是什么样的。请问能告诉我，在network文件夹哪个.py文件中是有关这一部分的吗？

**Comment by niujinshuchong** [comment]
@yanxiaojing16 

得到的深度图是相对深度，因为我们没有用到训练集中的深度图作为监督。预测的部分可以看Depth Decoder.
